### ISSUE TITLE
Add instructions step about increasing memory and CPUs available to Docker on Mac

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/RNA-Seq-Exercises#26]
This should be in the "Post Docker Install" instructions in this repository and preferably be is illustrated with screenshots.

On Mac this is how you do this: 
Click the Docker whale on the taskbar > `Preferences` > Navigate to the `Advanced` tab > Increase the resources available to Docker. 

For reference: On my MacBook (the potato chip ™️ ), I will have this set to CPUs: 2, Memory: 6.0 GiB, and Swap 1.0 GiB throughout our dry run.

**Comment by cansav09** [comment]
Does that mean you want me to also have them set it to 2, 6.0, and 1.0?

**Comment by jaclyn-taroni** [comment]
It depends on their computer. The idea is that we don't want Docker to use _all_ of their computer's resources. We're also going to need to see how today goes, but feel free to draft something up using this as a guide. Perhaps "leave 2GB free, don't use all of your CPUs"
