### ISSUE TITLE
2019 Chicago: Bring schedule up to date

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/RNA-Seq-Exercises#34]
Should this include links to the exercise notebooks (https://github.com/AlexsLemonade/training-modules/issues/78) ?

**Comment by cansav09** [comment]
Add that we are going to [The Berghoff](https://www.theberghoff.com/the-berghoff-restaurant-menu) for dinner to the schedule

**Comment by jaclyn-taroni** [comment]
Closed via #39
