### ISSUE TITLE
Chicago 2019: Update anywhere it says Houston -> Chicago 

### ISSUE THREAD

**Issue by cansav09** [AlexsLemonade/RNA-Seq-Exercises#37]
- [ ] README
- [ ] Docker-load.md (need tag ID so dependent on [#75 from training-modules](https://github.com/AlexsLemonade/training-modules/issues/75))
- [ ] Welcome slides - also dependent on [#75 from training-modules](https://github.com/AlexsLemonade/training-modules/issues/75)
- [ ] Check intro slides?

**Comment by jaclyn-taroni** [comment]
Closed via #39

**Comment by jaclyn-taroni** [comment]
I think the slides bits are best tracked elsewhere at this point.
