### ISSUE TITLE
Things to be added to Docker container

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/RNA-Seq-Exercises#6]
Running list of things to be added to `ccdl/training_rnaseq`

**Comment by jaclyn-taroni** [comment]
org.Hs.eg.db
`R -e "BiocInstaller::biocLite('org.Hs.eg.db')"`

**Comment by jaclyn-taroni** [comment]
ComplexHeatmap
`R -e "BiocInstaller::biocLite('ComplexHeatmap')"`

**Comment by jaclyn-taroni** [comment]
ggpubr

**Comment by jaclyn-taroni** [comment]
ggsignif
`devtools::install_github("const-ae/ggsignif", ref = "aadd9d44a360fc35fc3aef4b0fcdfdb7e1768d27")`

**Comment by cgreene** [comment]
I also threw `org.Dr.eg.db` in there b/c of our zebrafish folks. we may want to split these out later if the container size gets too large.
